platform :ios, '8.3'

use_frameworks!

target 'AnobiUIKit_Example' do
  pod 'AnobiUIKit', :path => '../'

  target 'AnobiUIKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
