platform :ios, '9.3'

use_frameworks!

target 'AnobiUIKit_Example' do
  pod 'AnobiUIKit', :path => '../'
  target 'AnobiUIKit_Tests' do
    inherit! :search_paths
  end
end

#post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#        config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
#        config.build_settings.delete('CODE_SIGNING_REQUIRED')
#    end
#end
